name: Changelog test
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Check version changes
      uses: EndBug/version-check@v1
      id: check
    - name: Parse Changelog # Exit if changelog not found
      id: changelog
      uses: ./scripts/changelog
      with:
        version: ${{ steps.check.outputs.version }}
    - run: echo ${{ steps.changelog.output.version }}\n${{ steps.changelog.output.changes }}
