name: Changelog test
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Check version changes
      uses: EndBug/version-check@v1
      id: check
    - name: Parse Changelog # Exit if changelog not found
      id: changelog
      env:
        INPUT_VERSION: ${{ needs.check.outputs.version }}
      run: node ./scripts/changelog
    - run: echo -e "${{ steps.changelog.outputs.version }}\n${{ steps.changelog.outputs.changes }}"
